#!/usr/bin/env bash
# scripts/build_and_publish.sh
set -uo pipefail

: "${FEISHU_APP_ID:?missing FEISHU_APP_ID}"
: "${FEISHU_APP_SECRET:?missing FEISHU_APP_SECRET}"
: "${FEISHU_FOLDER_TOKEN:?missing FEISHU_FOLDER_TOKEN}"
: "${AUR_PACKAGE_NAME:?missing AUR_PACKAGE_NAME}"
: "${AUR_GIT_NAME:?missing AUR_GIT_NAME}"
: "${AUR_GIT_EMAIL:?missing AUR_GIT_EMAIL}"
: "${AUR_SSH_PRIVATE_KEY:?missing AUR_SSH_PRIVATE_KEY}"
: "${GH_TOKEN:?missing GH_TOKEN}"
: "${GITHUB_REPOSITORY:?missing GITHUB_REPOSITORY}"

git config --global --add safe.directory /work
git config --global --add safe.directory '*'

ROOT="${GITHUB_WORKSPACE:-$PWD}"
WORKDIR="$ROOT/.ci-work"
DIST="$WORKDIR/dist"
META="$WORKDIR/meta"
AURGEN="$WORKDIR/aur-gen"
AURREPO="$WORKDIR/aur-repo"

rm -rf "$WORKDIR"
mkdir -p "$DIST" "$META" "$AURGEN"

echo "[DEBUG] DNS test"
getent hosts open.feishu.cn || true

echo "[DEBUG] TLS test"
curl -Ivs https://open.feishu.cn 2>&1 || true

emit_array_lines() {
  local file="$1" line
  while IFS= read -r line; do
    [[ -z "$line" ]] && continue
    line=${line//\'/\'\"\'\"\'}
    printf "    '%s'\n" "$line"
  done < "$file"
}

get_feishu_token() {
  curl -fsS -X POST \
    "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal" \
    -H "Content-Type: application/json" \
    -d "$(jq -nc --arg id "${FEISHU_APP_ID}" --arg secret "${FEISHU_APP_SECRET}" \
      '{app_id:$id, app_secret:$secret}')" \
  | jq -r '.tenant_access_token'
}

choose_latest_deb_zip() {
  jq -r '
    .data.files
    | map(select(.name | test("-deb\\.zip$")))
    | sort_by(.modified_time | tonumber)
    | last
    | [.name, .token]
    | @tsv
  '
}

extract_version_from_name() {
  python3 - "$1" <<'PY'
import re, sys
name = sys.argv[1]
m = re.match(r'^.+-([0-9][A-Za-z0-9._-]*)-deb\.zip$', name)
if not m:
    raise SystemExit(f"Cannot parse version from: {name}")
print(m.group(1))
PY
}

echo "[1/5] Query Feishu folder"
echo "[DEBUG] Requesting tenant_access_token"

TOKEN_RESPONSE_FILE="$WORKDIR/token_response.json"
TOKEN_HEADER_FILE="$WORKDIR/token_headers.txt"

HTTP_CODE=$(
curl -sS -L \
  -D "$TOKEN_HEADER_FILE" \
  -o "$TOKEN_RESPONSE_FILE" \
  -w "%{http_code}" \
  -X POST \
  "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal" \
  -H "Content-Type: application/json" \
  -d "$(jq -nc \
      --arg id "$FEISHU_APP_ID" \
      --arg secret "$FEISHU_APP_SECRET" \
      '{app_id:$id, app_secret:$secret}')"
)

CURL_EXIT=$?

echo "[DEBUG] curl exit code: $CURL_EXIT"
echo "[DEBUG] HTTP code: $HTTP_CODE"

echo "[DEBUG] Response headers:"
cat "$TOKEN_HEADER_FILE" || true

echo "[DEBUG] Response body:"
cat "$TOKEN_RESPONSE_FILE" || true

if [[ "$CURL_EXIT" != "0" ]]; then
  echo "[ERROR] curl failed"
  exit 1
fi

FEISHU_TOKEN="$(jq -r '.tenant_access_token // empty' "$TOKEN_RESPONSE_FILE")"

echo "[DEBUG] token length: ${#FEISHU_TOKEN}"

if [[ -z "$FEISHU_TOKEN" ]]; then
  echo "[ERROR] Failed to obtain tenant_access_token"
  exit 1
fi

echo "[DEBUG] Querying Feishu folder"

FOLDER_RESPONSE_FILE="$WORKDIR/folder_response.json"
FOLDER_HEADER_FILE="$WORKDIR/folder_headers.txt"

HTTP_CODE=$(
curl -sS -L \
  -D "$FOLDER_HEADER_FILE" \
  -o "$FOLDER_RESPONSE_FILE" \
  -w "%{http_code}" \
  -H "Authorization: Bearer ${FEISHU_TOKEN}" \
  "https://open.feishu.cn/open-apis/drive/v1/files?folder_token=${FEISHU_FOLDER_TOKEN}&limit=200"
)

CURL_EXIT=$?

echo "[DEBUG] curl exit code: $CURL_EXIT"
echo "[DEBUG] HTTP code: $HTTP_CODE"

echo "[DEBUG] Response headers:"
cat "$FOLDER_HEADER_FILE" || true

echo "[DEBUG] Response body:"
cat "$FOLDER_RESPONSE_FILE" || true

if [[ "$CURL_EXIT" != "0" ]]; then
  echo "[ERROR] folder request failed"
  exit 1
fi

FILES_JSON="$(cat "$FOLDER_RESPONSE_FILE")"

read -r FILE_NAME FILE_TOKEN < <(printf '%s' "$FILES_JSON" | choose_latest_deb_zip)
if [[ -z "${FILE_NAME:-}" || -z "${FILE_TOKEN:-}" ]]; then
  echo "No .deb.zip file found in folder"
  exit 1
fi

PKGVER="$(extract_version_from_name "$FILE_NAME")"
if [[ -z "$PKGVER" ]]; then
  echo "Cannot parse version from: $FILE_NAME"
  exit 1
fi

echo "Selected file: $FILE_NAME"
echo "Version: $PKGVER"

echo "[2/5] Download outer zip and unpack .deb"
curl -fsS -X GET "https://open.feishu.cn/open-apis/drive/v1/files/${FILE_TOKEN}/download" \
  -H "Authorization: Bearer ${FEISHU_TOKEN}" \
  -o "$WORKDIR/source.zip"

mkdir -p "$WORKDIR/outer"
unzip -q "$WORKDIR/source.zip" -d "$WORKDIR/outer"

DEB_FILE="$(find "$WORKDIR/outer" -type f -name '*.deb' | sort | head -n1)"
if [[ -z "${DEB_FILE:-}" ]]; then
  echo "No .deb file found inside zip"
  exit 1
fi

echo "[3/5] Convert .deb to Arch package with debtap"
debtap -u
debtap -Q -p -o "$DIST" "$DEB_FILE"

PKG_FILE="$(find "$DIST" -type f -name '*.pkg.tar.*' | sort | tail -n1)"
if [[ -z "${PKG_FILE:-}" ]]; then
  echo "No Arch package generated by debtap"
  exit 1
fi

mv "$PKG_FILE" "$DIST/${AUR_PACKAGE_NAME}-${PKGVER}-1-x86_64.pkg.tar.zst"
PKG_FILE="$(find "$DIST" -type f -name '*.pkg.tar.*' | sort | tail -n1)"
PKG_FILE="$DIST/${AUR_PACKAGE_NAME}-${PKGVER}-1-x86_64.pkg.tar.zst"
PKG_BASENAME="$(basename "$PKG_FILE")"
PKG_SHA256="$(sha256sum "$PKG_FILE" | awk '{print $1}')"

mkdir -p "$META"
bsdtar -xOf "$PKG_FILE" .PKGINFO | awk -F' = ' '
  /^depend = /{print $2}
' | sort -u > "$META/depends"

bsdtar -xOf "$PKG_FILE" .PKGINFO | awk -F' = ' '
  /^optdepend = /{print $2}
' | sort -u > "$META/optdepends"

bsdtar -xOf "$PKG_FILE" .PKGINFO | awk -F' = ' '
  /^provides = /{print $2}
' | sort -u > "$META/provides"

bsdtar -xOf "$PKG_FILE" .PKGINFO | awk -F' = ' '
  /^conflict = /{print $2}
' | sort -u > "$META/conflicts"

PKG_DESC="Closed-source package distributed via GitHub Release"
REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
ASSET_URL="${REPO_URL}/releases/download/v${PKGVER}/${PKG_BASENAME}"

echo "[4/5] Generate AUR PKGBUILD wrapper"
mkdir -p "$AURGEN"

cat > "$AURGEN/PKGBUILD" <<EOF
pkgname=${AUR_PACKAGE_NAME}
pkgver=${PKGVER}
pkgrel=1
pkgdesc='${PKG_DESC}'
arch=('x86_64')
url='${REPO_URL}'
license=('custom:proprietary')
makedepends=('libarchive')
depends=(
$(emit_array_lines "$META/depends")
)
optdepends=(
$(emit_array_lines "$META/optdepends")
)
provides=(
$(emit_array_lines "$META/provides")
)
conflicts=(
$(emit_array_lines "$META/conflicts")
)
source=(
  "${PKG_BASENAME}::${ASSET_URL}"
)
sha256sums=(
  '${PKG_SHA256}'
)
noextract=(
  '${PKG_BASENAME}'
)

package() {
  bsdtar --exclude='.PKGINFO' --exclude='.BUILDINFO' --exclude='.MTREE' --exclude='.INSTALL' \
    -xpf "\$srcdir/${PKG_BASENAME}" -C "\$pkgdir"
}
EOF

cd "$AURGEN"

cat > .SRCINFO <<EOF
pkgbase = ${AUR_PACKAGE_NAME}
	pkgdesc = ${PKG_DESC}
	pkgver = ${PKGVER}
	pkgrel = 1
	url = ${REPO_URL}
	arch = x86_64
	license = custom:proprietary
EOF

while read -r dep; do
  [[ -n "$dep" ]] && echo "	depends = $dep" >> .SRCINFO
done < "$META/depends"

while read -r dep; do
  [[ -n "$dep" ]] && echo "	optdepends = $dep" >> .SRCINFO
done < "$META/optdepends"

while read -r dep; do
  [[ -n "$dep" ]] && echo "	provides = $dep" >> .SRCINFO
done < "$META/provides"

while read -r dep; do
  [[ -n "$dep" ]] && echo "	conflicts = $dep" >> .SRCINFO
done < "$META/conflicts"

cat >> .SRCINFO <<EOF
	source = ${PKG_BASENAME}::${ASSET_URL}
	sha256sums = ${PKG_SHA256}

pkgname = ${AUR_PACKAGE_NAME}
EOF

echo "[5/5] Publish GitHub Release"
export GH_TOKEN
if gh release view "v${PKGVER}" >/dev/null 2>&1; then
  gh release upload "v${PKGVER}" "$PKG_FILE" --clobber
else
  gh release create "v${PKGVER}" "$PKG_FILE" \
    --title "${AUR_PACKAGE_NAME} ${PKGVER}" \
    --notes "Automated build from Feishu folder ${FEISHU_FOLDER_TOKEN}"
fi

echo "[5/5] Push AUR package"
eval "$(ssh-agent -s)"
install -d -m 700 ~/.ssh
printf '%s\n' "$AUR_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
chmod 600 ~/.ssh/id_ed25519
ssh-add ~/.ssh/id_ed25519
ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts

rm -rf "$AURREPO"
git clone "ssh://aur@aur.archlinux.org/${AUR_PACKAGE_NAME}.git" "$AURREPO"
cd "$AURREPO"

cp "$AURGEN/PKGBUILD" .
cp "$AURGEN/.SRCINFO" .

git config user.name "$AUR_GIT_NAME"
git config user.email "$AUR_GIT_EMAIL"

git add PKGBUILD .SRCINFO
if git diff --cached --quiet; then
  echo "AUR repo already up to date"
else
  git commit -m "Update to ${PKGVER}"
  git push
fi

echo "Done."
